"""Initial schema setup

Revision ID: 333e4648ce84
Revises:
Create Date: 2025-07-30 16:52:53.952155

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "333e4648ce84"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "conversation_chunks",
        "conversation_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_constraint(
        "conversation_order_unique", "conversation_chunks", type_="unique"
    )
    op.drop_index(
        "ix_conversation_chunks_conversation_id", table_name="conversation_chunks"
    )
    op.drop_index("ix_conversation_chunks_timestamp", table_name="conversation_chunks")
    op.create_index(
        "ix_conversation_chunks_conversation_order",
        "conversation_chunks",
        ["conversation_id", "order_index"],
        unique=True,
    )
    op.create_index(
        op.f("ix_conversation_chunks_id"), "conversation_chunks", ["id"], unique=False
    )
    op.drop_constraint(
        "conversation_chunks_conversation_id_fkey",
        "conversation_chunks",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "conversation_chunks", "conversations", ["conversation_id"], ["id"]
    )
    op.drop_index("ix_conversations_created_at", table_name="conversations")
    op.create_index(op.f("ix_conversations_id"), "conversations", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_conversations_id"), table_name="conversations")
    op.create_index(
        "ix_conversations_created_at", "conversations", ["created_at"], unique=False
    )
    op.drop_constraint(None, "conversation_chunks", type_="foreignkey")
    op.create_foreign_key(
        "conversation_chunks_conversation_id_fkey",
        "conversation_chunks",
        "conversations",
        ["conversation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_conversation_chunks_id"), table_name="conversation_chunks")
    op.drop_index(
        "ix_conversation_chunks_conversation_order", table_name="conversation_chunks"
    )
    op.create_index(
        "ix_conversation_chunks_timestamp",
        "conversation_chunks",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_conversation_chunks_conversation_id",
        "conversation_chunks",
        ["conversation_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "conversation_order_unique",
        "conversation_chunks",
        ["conversation_id", "order_index"],
    )
    op.alter_column(
        "conversation_chunks",
        "conversation_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###
